package com.example.belajarandroidpemula;

import java.util.ArrayList;

public class DataJamTangan {
    private static String[][] data = new String[][]{
            {"G-Shock GA-700-2ADR", "Rp2.200.000", "https://www.jamtangan.com/images/product/casio/GA-700-2ADR/1l.jpg", "G-Shock, Bulat, Digital dan Analog", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock DW-5600-BB-1ADR", "Rp2.300.000", "https://www.jamtangan.com/images/product/casio/DW-5600BB-1JF/1l.jpg", "G-Shock, Kotak, Digital", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock GD-400-3DR", "Rp2.500.000", "https://www.jamtangan.com/images/product/casio/GD-400-3DR/1l.jpg", "G-Shock, Digital, Karet", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock DW-6900BBA-1DR", "Rp2.400.000", "https://www.jamtangan.com/images/product/casio/DW-6900BB-1JF/1l.jpg", "G-Shock, Digital, Bulat", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock GA-800-4ADR", "Rp2.450.000", "https://www.jamtangan.com/images/product/casio/GA-800-4ADR/1l.jpg", "G-Shock, Bulat, Digital dan Analog", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock GD-X6900T-8DR", "Rp3.375.000", "https://www.jamtangan.com/images/product/casio/GD-X6900TC-8DR/1l.jpg", "G-Shock, Digital, Army", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock GA-110RG-1ADR", "Rp3.500.000", "https://images-na.ssl-images-amazon.com/images/I/61lTP2cRkQL._UX342_.jpg", "G-Shock, Bulat, Digital dan Analog", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock G-9000-3VDR", "Rp2.550.000", "https://www.jamtangan.com/images/product/casio/G-9000-3VDR/1l.jpg", "G-Shock, Bulat, Digital", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock GA-100CM-4ADR", "Rp3.550.000", "https://www.jamtangan.com/images/product/casio/GA-100CM-4ADR/1l.jpg", "G-Shock, Bulat, Army", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."},
            {"G-Shock GBD-800UC-3DR", "Rp2.400.000", "https://c.76.my/Malaysia/casio-g-shock-gbd-800uc-3a-bluetooth-watch-100-original-gpeople-1906-30-Gpeople@4.jpg", "G-Shock, Bulat, Casual", "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Lacus sed viverra tellus in hac habitasse. Neque aliquam vestibulum morbi blandit cursus. Pretium nibh ipsum consequat nisl vel pretium. Tellus id interdum velit laoreet id donec ultrices tincidunt. Nunc lobortis mattis aliquam faucibus. Blandit libero volutpat sed cras ornare. Aliquam faucibus purus in massa tempor nec feugiat nisl. Platea dictumst vestibulum rhoncus est. Magna eget est lorem ipsum dolor sit amet. Nisi porta lorem mollis aliquam. Quam nulla porttitor massa id neque aliquam vestibulum morbi blandit. Odio euismod lacinia at quis risus. Egestas tellus rutrum tellus pellentesque eu tincidunt. Purus faucibus ornare suspendisse sed. Velit laoreet id donec ultrices tincidunt arcu non sodales.\n" +
                    "\n" +
                    "Lacus sed viverra tellus in hac habitasse platea. Lobortis feugiat vivamus at augue. Morbi tincidunt augue interdum velit euismod in pellentesque. Tellus in hac habitasse platea dictumst. Massa id neque aliquam vestibulum morbi blandit cursus risus at. Rhoncus est pellentesque elit ullamcorper. Placerat orci nulla pellentesque dignissim enim. Sit amet porttitor eget dolor. Risus quis varius quam quisque id diam vel quam elementum. Imperdiet dui accumsan sit amet. Vel fringilla est ullamcorper eget nulla facilisi etiam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper. Purus gravida quis blandit turpis cursus. Nulla facilisi morbi tempus iaculis urna id volutpat lacus. Ultricies lacus sed turpis tincidunt id."}
    };

    public static ArrayList<JamTangan> getListData() {
        ArrayList<JamTangan> list = new ArrayList<>();
        for (String[] aData : data) {
            JamTangan jamTangan = new JamTangan();
            jamTangan.setMerk(aData[0]);
            jamTangan.setPrice(aData[1]);
            jamTangan.setPhoto(aData[2]);
            jamTangan.setTag(aData[3]);
            jamTangan.setDescription(aData[4]);
            list.add(jamTangan);
        }
        return list;
    }
}
